### PR TITLE
Use standard d2l-icons for profile pic

### PR DESCRIPTION
**Pull request by apalaniuk**
https://rally1.rallydev.com/#/89963236876d/detail/userstory/122992170488

### CODE REVIEW

**Comment by jstefaniuk-d2l** [comment]
From what I remember, user tile looks pretty bad with this icon

**Comment by ryantmer** [comment]
Hmm, yeah I guess it is larger and whatnot. Well, one less icon at least!

**Comment by ryantmer** [comment]
Side note: the icon doesn't look like it's changed since 3.x.x, so shouldn't need the bump unless you want to deal with all the bower conflicts :P

**Comment by jstefaniuk-d2l** [comment]
Confirmed with Bob, user tile remains the same

**Comment by apalaniuk** [comment]
@ryantmer Hrm, local Bower was reporting 3.whatever installed but `profile-pic` was missing from source - I assumed it was a newer icon but clearly not. I'll roll that stuff back. Thanks!

**Comment by ryantmer** [comment]
Oh dang, yeah sorry - I was looking at `profile-default`. My bad!

**Comment by ryantmer** [comment]
Oh, I guess this is a breaking change eh? Since bower is shite and all.

**Pull request merged**
